# https://docs.travis-ci.com/user/languages/php/
language: php
dist: bionic
php:
  - 7.3
# https://app.swaggerhub.com/settings/apiKey
# env:
#   - API_KEY: "string"
before_script:
  - yes | pecl install yaml
script:
  - php -f main.php